fix: husky only pre-commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,13 @@
 #!/usr/bin/env sh
-pnpm run lint && pnpm run test
+pnpm run lint
 
+echo "Running tests..."
+
+pnpm run test
+# Check if tests passed
+if [ $? -ne 0 ]; then
+  echo "Tests failed. Please fix the tests before pushing."
+  exit 1
+fi
+echo "Tests passed. Proceeding with push..."
 
